// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFQW1ZQCrdfd6q2gcWDby9KLBM_Bycw2Y',
    appId: '1:612684328267:web:964a5fa9559cef04584cce',
    messagingSenderId: '612684328267',
    projectId: 'attendace-e7b79',
    authDomain: 'attendace-e7b79.firebaseapp.com',
    storageBucket: 'attendace-e7b79.appspot.com',
    measurementId: 'G-EHG11JJ5BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNqfRmVU407TanyGC91V_jWpK3sIZIlTs',
    appId: '1:612684328267:android:c341da73f8352f45584cce',
    messagingSenderId: '612684328267',
    projectId: 'attendace-e7b79',
    storageBucket: 'attendace-e7b79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQTxAa9ulBM9tFRlYzGwc7T8xCpHsZK_M',
    appId: '1:612684328267:ios:c443b10926232822584cce',
    messagingSenderId: '612684328267',
    projectId: 'attendace-e7b79',
    storageBucket: 'attendace-e7b79.appspot.com',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQTxAa9ulBM9tFRlYzGwc7T8xCpHsZK_M',
    appId: '1:612684328267:ios:c443b10926232822584cce',
    messagingSenderId: '612684328267',
    projectId: 'attendace-e7b79',
    storageBucket: 'attendace-e7b79.appspot.com',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFQW1ZQCrdfd6q2gcWDby9KLBM_Bycw2Y',
    appId: '1:612684328267:web:5183a9cdce789452584cce',
    messagingSenderId: '612684328267',
    projectId: 'attendace-e7b79',
    authDomain: 'attendace-e7b79.firebaseapp.com',
    storageBucket: 'attendace-e7b79.appspot.com',
    measurementId: 'G-EE339SB5HL',
  );
}
